version: "3.9"
services:
  mysql:
    restart: always
    platform: linux/x86_64
    container_name: "mysql"
    command: [ "--max-allowed-packet=67108864" ]
    image: mysql:5.7
    ports:
      - 3306:3306
    environment:
      - MYSQL_ROOT_PASSWORD=password
      - MYSQL_DATABASE=mysql
      - MYSQL_USER=user
      - MYSQL_PASSWORD=password
      - LANG=C.UTF-8
    volumes:
      - ./mysql-data:/var/lib/mysql
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
      - ./data:/data